{% set version = "0.12.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nodbi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nodbi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nodbi/nodbi_{{ version }}.tar.gz
  sha256: a2af7755f12164dc0bd2ac8eb09976b61d3a5650a127d76fa0a7c9153bd36724

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
    - r-r.utils
    - r-v8
    - r-jqr
    - r-jsonlite
    - r-stringi
    - r-uuid
  run:
    - r-base
    - r-dbi
    - r-r.utils
    - r-v8
    - r-jqr
    - r-jsonlite
    - r-stringi
    - r-uuid

test:
  commands:
    - $R -e "library('nodbi')"           # [not win]
    - "\"%R%\" -e \"library('nodbi')\""  # [win]

about:
  home: https://docs.ropensci.org/nodbi/, https://github.com/ropensci/nodbi
  license: MIT
  summary: Simplified document database access and manipulation, providing a common API across supported 'NoSQL' databases 'Elasticsearch', 'CouchDB', 'MongoDB' as well as 'SQLite/JSON1', 'PostgreSQL', and 'DuckDB'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
